version: 0.2

env:
  parameter-store:
    GIT_USER: "/CodeBuild/Git_USER"
    GIT_PASS: "/CodeBuild/Git_PASS"

phases:
  install:
    commands:
      - echo Executing install phase
      - echo $CODEBUILD_WEBHOOK_TRIGGER
      - echo $CODEBUILD_WEBHOOK_BASE_REF
      - echo $CODEBUILD_WEBHOOK_ACTOR_ACCOUNT_ID
      - echo $CODEBUILD_WEBHOOK_EVENT


      - echo MPI setup for Docker
      - mkdir -p /var/run/sshd
      - ssh-keygen -A
      - sed -i 's/#PermitRootLogin yes/PermitRootLogin yes/g' /etc/ssh/sshd_config
      - sed -i 's/#RSAAuthentication yes/RSAAuthentication yes/g' /etc/ssh/sshd_config
      - sed -i 's/#PubkeyAuthentication yes/PubkeyAuthentication yes/g' /etc/ssh/sshd_config

      - groupadd jcsda -g 9999
      - useradd jcsdauser
      - mkdir -p /jcsda /build_container
      - chown -R jcsdauser:jcsda /build_container  /usr/local
      - chmod 6755 /jcsda /build_container /usr/local

      - mkdir /jcsda/.ssh ; echo "StrictHostKeyChecking no" > /jcsda/.ssh/config
      - mkdir -p /jcsda/.openmpi
      - mkdir -p /home/jcsdauser/.openmpi

      - cp default-mca-params.conf /home/jcsdauser/.openmpi/mca-params.conf
      - cat /home/jcsdauser/.openmpi/mca-params.conf
      - chown -R jcsdauser:jcsda /jcsda/

      - su - jcsdauser -c "ssh-keygen -f /jcsda/.ssh/id_rsa -t rsa -N ''
        && chmod 600 /jcsda/.ssh/config
        && chmod 700 /jcsda/.ssh
        && cp /jcsda/.ssh/id_rsa.pub /jcsda/.ssh/authorized_keys
        && echo MPI setup for Docker done"
      - su - jcsdauser -c "echo $CC
        && echo $CXX
        && echo $FC
        && whereis mpicc"

      ## cannot source /etc/bash.bashrc so copy what's there for root
      - sed '12s/INTEL_TARGET_ARCH=/INTEL_TARGET_ARCH=intel64/' /opt/intel/compilers_and_libraries/linux/bin/compilervars.sh
      - export COMPILERVARS_ARCHITECTURE=intel64
      - export COMPILERVARS_PLATFORM=linux
      - . /opt/intel/compilers_and_libraries/linux/bin/compilervars.sh
      - export FC=mpiifort
      - export CC=mpiicc
      - export CXX=mpiicpc
      - export PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - export LD_LIBRARY_PATH=/usr/local/lib
      - export LIBRARY_PATH=/usr/local/lib
      - . /opt/intel/compilers_and_libraries/linux/bin/compilervars.sh

  pre_build:
    commands:
      - echo Executing pre_build phase
      - git lfs install # creates .gitconfig
      - cp ~/.gitconfig /home/jcsdauser/

      - if [ "$CODEBUILD_WEBHOOK_EVENT" = "PULL_REQUEST_MERGED" ];
        then export CODEBUILD_GIT_BRANCH="develop";
        echo $CODEBUILD_GIT_BRANCH;
        echo "Merging to develop";
        else CODEBUILD_GIT_BRANCH="$(git branch -a --contains $CODEBUILD_SOURCE_VERSION | sed -n 2p | awk '{ printf $1 }')";
        export CODEBUILD_GIT_BRANCH=${CODEBUILD_GIT_BRANCH#remotes/origin/};
        fi

      - echo "CODEBUILD_GIT_BRANCH=${CODEBUILD_GIT_BRANCH}"
      - echo "CODEBUILD_SOURCE_VERSION=${CODEBUILD_SOURCE_VERSION}"

      - git clone https://$GIT_USER:$GIT_PASS@github.com/jcsda/fv3-bundle fv3-bundle
      - cd fv3-bundle
      - git checkout $CODEBUILD_GIT_BRANCH || echo "No branch named $CODEBUILD_GIT_BRANCH in fv3-bundle repo"
      - cd $CODEBUILD_SRC_DIR

      # FV3-JEDI (testing repo)
      - git clone -b $CODEBUILD_GIT_BRANCH https://$GIT_USER:$GIT_PASS@github.com/jcsda/fv3-jedi fv3-bundle/fv3-jedi

      # fv3-jedi-lm
      - git clone https://$GIT_USER:$GIT_PASS@github.com/jcsda/fv3-jedi-linearmodel fv3-bundle/fv3-jedi-lm
      - cd fv3-bundle/fv3-jedi-lm
      - git checkout $CODEBUILD_GIT_BRANCH || echo "No branch named $CODEBUILD_GIT_BRANCH in fv3-jedi-lm repo"
      - cd $CODEBUILD_SRC_DIR

      # crtm
      - git clone https://$GIT_USER:$GIT_PASS@github.com/jcsda/crtm fv3-bundle/crtm
      - cd fv3-bundle/crtm
      - git checkout $CODEBUILD_GIT_BRANCH || echo "No branch named $CODEBUILD_GIT_BRANCH in crtm repo"
      - cd $CODEBUILD_SRC_DIR

      # ioda
      - git clone https://$GIT_USER:$GIT_PASS@github.com/jcsda/ioda fv3-bundle/ioda
      - cd fv3-bundle/ioda
      - git checkout $CODEBUILD_GIT_BRANCH || echo "No branch named $CODEBUILD_GIT_BRANCH in ioda repo"
      - cd $CODEBUILD_SRC_DIR

      # disable git-lfs
      - git lfs install --skip-smudge

      # saber
      - git clone https://$GIT_USER:$GIT_PASS@github.com/jcsda/saber fv3-bundle/saber
      - cd fv3-bundle/saber
      - git checkout $CODEBUILD_GIT_BRANCH || echo "No branch named $CODEBUILD_GIT_BRANCH in saber repo"
      - cd $CODEBUILD_SRC_DIR

      # oops
      - git clone https://$GIT_USER:$GIT_PASS@github.com/jcsda/oops fv3-bundle/oops
      - cd fv3-bundle/oops
      - git checkout $CODEBUILD_GIT_BRANCH || echo "No branch named $CODEBUILD_GIT_BRANCH in oops repo"
      - cd $CODEBUILD_SRC_DIR

      # ufo
      - git clone https://$GIT_USER:$GIT_PASS@github.com/jcsda/ufo fv3-bundle/ufo
      - cd fv3-bundle/ufo
      - git checkout $CODEBUILD_GIT_BRANCH || echo "No branch named $CODEBUILD_GIT_BRANCH in ufo repo"
      - cd $CODEBUILD_SRC_DIR

      # femps
      - git clone https://$GIT_USER:$GIT_PASS@github.com/jcsda/femps fv3-bundle/femps
      - cd fv3-bundle/femps
      - git checkout $CODEBUILD_GIT_BRANCH || echo "No branch named $CODEBUILD_GIT_BRANCH in femps repo"
      - cd $CODEBUILD_SRC_DIR

      # FV3 based model and/or FMS
      - git clone -b dev/master-ecbuild https://$GIT_USER:$GIT_PASS@github.com/jcsda/FMS fv3-bundle/fms
      - cd $CODEBUILD_SRC_DIR

      # fckit
      - git clone https://$GIT_USER:$GIT_PASS@github.com/jcsda/fckit fv3-bundle/fckit
      - cd fv3-bundle/fckit
      - git checkout $CODEBUILD_GIT_BRANCH || echo "No branch named $CODEBUILD_GIT_BRANCH in fckit repo"
      - cd $CODEBUILD_SRC_DIR

      # atlas
      - git clone https://$GIT_USER:$GIT_PASS@github.com/jcsda/atlas fv3-bundle/atlas
      - cd fv3-bundle/atlas
      - git checkout $CODEBUILD_GIT_BRANCH || echo "No branch named $CODEBUILD_GIT_BRANCH in atlas repo"
      - cd $CODEBUILD_SRC_DIR

      # geos-aero
#      - git clone https://$GIT_USER:$GIT_PASS@github.com/jcsda/geos-aero fv3-bundle/geos-aero
#      - cd fv3-bundle/geos-aero
#      - git checkout $CODEBUILD_GIT_BRANCH || echo "No branch named $CODEBUILD_GIT_BRANCH in geos-aero repo"
#      - cd $CODEBUILD_SRC_DIR

      - ls
      - pwd
      - mv fv3-bundle /jcsda/
      - cd /jcsda/fv3-bundle
      - pwd
      - ls
      - sed -i 's/BRANCH dev\/master-ecbuild UPDATE  //' CMakeLists.txt
      - sed -i 's/BRANCH develop UPDATE //' CMakeLists.txt
      - sed -i '/PROJECT eckit/d' CMakeLists.txt
#      - sed -i -e '/ecbuild_bundle( PROJECT crtm/i\
#        ecbuild_bundle( PROJECT geos-aero GIT "https://github.com/JCSDA/geos-aero.git" )' CMakeLists.txt
      - cat CMakeLists.txt

  build:
    commands:
      - echo Executing build phase
      ## cannot source /etc/bash.bashrc so copy what's there for jscdauser
      - su - jcsdauser -c "export COMPILERVARS_ARCHITECTURE=intel64
        && export COMPILERVARS_PLATFORM=linux
        && . /opt/intel/compilers_and_libraries/linux/bin/compilervars.sh
        && export FC=mpiifort
        && export CC=mpiicc
        && export CXX=mpiicpc
        && export PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        && export LD_LIBRARY_PATH=/usr/local/lib
        && export LIBRARY_PATH=/usr/local/lib
        && . /opt/intel/compilers_and_libraries/linux/bin/compilervars.sh
        && cd /build_container
        && ls
        && ecbuild /jcsda/fv3-bundle/
        && cd fv3-jedi
        && make -j4"

      - export BUILD_STATUS="0"
      - echo $BUILD_STATUS
      - echo $CODEBUILD_BUILD_SUCCEEDING

      - if [ "$CODEBUILD_BUILD_SUCCEEDING" = "1" ];
        then export BUILD_STATUS="1";
        echo "Build passed";
        fi
      - echo $BUILD_STATUS

      - su - jcsdauser -c "export COMPILERVARS_ARCHITECTURE=intel64
        && export COMPILERVARS_PLATFORM=linux
        && . /opt/intel/compilers_and_libraries/linux/bin/compilervars.sh
        && export FC=mpiifort
        && export CC=mpiicc
        && export CXX=mpiicpc
        && export PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        && export LD_LIBRARY_PATH=/usr/local/lib
        && export LIBRARY_PATH=/usr/local/lib
        && . /opt/intel/compilers_and_libraries/linux/bin/compilervars.sh
        && cd /build_container/fv3-jedi
        && ctest"
  post_build:
    commands:
      - echo Executing post_build phase
      - echo $CODEBUILD_BUILD_SUCCEEDING
      - if [ "$BUILD_STATUS" = "1" ] && [ "$CODEBUILD_BUILD_SUCCEEDING" = "0" ];
        then echo "Build passed, rerun failed tests";
        su - jcsdauser -c "export COMPILERVARS_ARCHITECTURE=intel64
        && export COMPILERVARS_PLATFORM=linux
        && . /opt/intel/compilers_and_libraries/linux/bin/compilervars.sh
        && export FC=mpiifort
        && export CC=mpiicc
        && export CXX=mpiicpc
        && export PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        && export LD_LIBRARY_PATH=/usr/local/lib
        && export LIBRARY_PATH=/usr/local/lib
        && . /opt/intel/compilers_and_libraries/linux/bin/compilervars.sh
        && cd /build_container/fv3-jedi
        && echo $LD_LIBRARY_PATH
        && ctest -VV --rerun-failed";
        else echo "Build failed";
        fi
